experiment_name: nih_chestxray_federated_baseline
seed: 42
num_clients: 50
global_rounds: 10
local_epochs: 1
batch_size: 16
lr: 1e-3
model_backbone: resnet18
data:
  root: ./data/nih-chest-xray
  train_dir: ./data/nih-chest-xray/train
  val_dir: ./data/nih-chest-xray/val
  test_dir: ./data/nih-chest-xray/test
outputs:
  models_dir: ./models
  results_dir: ./results
